spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/bankcards}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:HYf663x1+}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml
    enabled: true
    default-schema: public

jwt:
  secret: ${JWT_SECRET:dGhpcy1pcy1hLXNlY3JldC1rZXktd2l0aC0zMi1ieXRlcy1sZW5ndGgtZm9yLWp3dC1hdXRoZW50aWNhdGlvbg==}
  expiration: ${JWT_EXPIRATION:86400000}

app:
  admin:
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD:ultraPassword}
    email: ${ADMIN_EMAIL:admin@company.com}

card:
  encryption:
    password: ${CARD_ENCRYPTION_PASSWORD:anotherUltraPassword}
    salt: ${CARD_ENCRYPTION_SALT:randomSaltForCardsTable12356}

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    com.gordeev.bankcards: INFO
  file:
    name: /app/logs/application.log